# k8s/base/payment-service/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  labels:
    app: payment-service
    app.kubernetes.io/part-of: family-hobbies-manager
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8083"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/familyhobbies_payments"
  SPRING_DATASOURCE_USERNAME: "familyhobbies_pay"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  HELLOASSO_API_BASE_URL: "https://api.helloasso-sandbox.com/v5"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
