# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: family-hobbies-dev

commonLabels:
  app.kubernetes.io/part-of: family-hobbies-manager
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - secrets/secrets.yaml
  # Infrastructure
  - postgresql/statefulset.yaml
  - postgresql/service.yaml
  - postgresql/pvc.yaml
  - kafka/statefulset.yaml
  - kafka/service.yaml
  # Microservices
  - discovery-service/deployment.yaml
  - discovery-service/service.yaml
  - discovery-service/configmap.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/route.yaml
  - api-gateway/configmap.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - user-service/configmap.yaml
  - association-service/deployment.yaml
  - association-service/service.yaml
  - association-service/configmap.yaml
  - payment-service/deployment.yaml
  - payment-service/service.yaml
  - payment-service/configmap.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - notification-service/configmap.yaml
  # Frontend
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/route.yaml
